name: "Hugo Notes"
description: "Transform my personal notes into Hugo content"
author: "Alexandre Lamberty <mail@alexandrelamberty.com>"
inputs:
  source:
    description: "Source folder"
    required: true
  destination:
    description: "Destination folder"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source }}
    - ${{ inputs.destination }}
branding:
  icon: "file-text"
  color: "blue"
